### ISSUE TITLE
Cura  5.3 & 5.4

### ISSUE THREAD

**Issue by FinboySlick** [phnxdrgn536/FLSun-v400#37]
First and foremost, thank you for the profile.  I've updated my v400 to official Klipper and started using your Cura profile.

I have a weird issue however.  I can only start cura 5.3 (or 5.4 now) about twice before it decides to crash on boot when I install your profile.  I have to wipe the settings directory, setup a new (factory) v400 profile, then overwrite those files with the ones provided here.  Which lets me use Cura once or twice before I have to repeat the process again.

This could be due to the fact that I am on linux, however, using your files with 5.2 appears to work well, I haven't had that problem yet.  There might be something I am doing wrong with the installation process.  Are there specif changes to later version of Cura that requires slight modifications to the files provided here?

Here is the type of error Cura 5.4 gives me when it is trying to import settings from 5.2 (with your profile), this might provide hints as to what is wrong:

```
Traceback (most recent call last):
  File "cura/CuraApplication.py", line 1132, in event
    return super().event(event)
  File "UM/Qt/QtApplication.py", line 502, in event
    event._function_event.call()
  File "UM/Event.py", line 218, in call
    self._function(*self._args, **self._kwargs)
  File "cura/Settings/MachineManager.py", line 181, in setInitialActiveMachine
    self.setActiveMachine(active_machine_id)
  File "cura/Settings/MachineManager.py", line 381, in setActiveMachine
    self._validateVariantsAndMaterials(global_stack)
  File "cura/Settings/MachineManager.py", line 399, in _validateVariantsAndMaterials
    material_node = variant_node.materials.get(extruder.material.getMetaDataEntry("base_file"))
AttributeError: 'NoneType' object has no attribute 'materials'
```

**Comment by phnxdrgn536** [comment]
I will check and see if they have changed the way cura handles profiles but
it should just be putting the files in the proper folder (5.1, 5.2, 5.3,
ETC)

**Comment by gestalt73** [comment]
Can confirm, the imported cura profile is crashing the same way in 5.4.  The latest cura build that works is 5.3.1, although sometimes I get a crash on launch then need to relaunch it.

In 5.6 and 5.7 the slicer crashes.

**Comment by FinboySlick** [comment]
I started looking into this again last week to see if I could get Cura 5.6.0 to work.  One of the things it doesn't like is numerical names for variants.  I fixed it by changing 'name = 0.4' into 'name = 0.4 mm'  It also cannot handle 'setting_version = 20', I tried 22 instead and that seemed to get through but I'm not sure of the implications.

Even with those changes, it crashes with:
ERROR - [MainThread] cura.Settings.MachineManager.setVariantByName [1578]: There is no variant with the name .

So there's probably something else it can't convert that I haven't found yet.

Should flsun_v400.def.json be this large?  I have a weird feeling that it sets *everything* instead of just inheriting and then overriding defaults.  The latter would make it a lot easier to maintain.

**Comment by phnxdrgn536** [comment]
The larger def.JSON file is because I’ve changed default “alarms” too. In
cura do you notice if you put a parameter out of the spec of the printer it
will turn yellow or red? Well the default speed is 200mm so anything above
that would cause the yellow caution and since the V400 originally was rated
for 400mm it was annoying to put it at a value the printer could handle put
cura always turned it yellow as a caution.

As for the setting_version it’s basically telling cura what version of the
code library to use so naturally newer versions of cura will require newer
versions of the settings and might not support legacy versions. That
appears to be what is happening for 5.6.0

**Comment by gestalt73** [comment]
in case it helps with the troubleshooting here's  the json for seemecnc artemis exported from 5.7.

[Cura-seemecnc-artemis.zip](https://github.com/phnxdrgn536/FLSun-v400/files/14489574/Cura-seemecnc-artemis.zip)

**Comment by phnxdrgn536** [comment]
Awesome I’ll definitely take a look at it

**Comment by gestalt73** [comment]
you know it's funny, sometimes when I launch 5.3.1 with the profile it crashes, all I have to do is launch it again or maybe one more time then I'm good to go.

I'm also going to start fiddling with the .json to see what needs to be updated for 5.6+.

**Comment by gestalt73** [comment]
I'm not sure if it's a clue, but when I export a project with profile in 5.3.1, the printer.json is blank if it's all standard settings.

In 5.7 the same printer profile exports eVeRyThInG.  I wonder if they did away with delta / default values and a custom profile has to call out all settings?  I'll give it a shot this weekend.
